### ISSUE TITLE
Peer review hw05 for Mike Marin

### ISSUE THREAD

**Issue by jdewstewart** [STAT545-UBC-hw-2019-20/stat545-hw-MarinStatsLectures#10]
Peer-Review HW-05 for Mike Marin

----------------------------------------------------
Topic                       | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding accuracy**            | :heavy_check_mark: |  |  |
**Writing**         		|   :heavy_check_mark: |  ||
**Visual quality**   		 |  :heavy_check_mark: ||  |
**Mechanics**   		 |  :heavy_check_mark:  |  ||
**HTML file** 			| :heavy_check_mark: |  |  |

**Remarks:**

- *Great, thorough explanation of here::here*
- *Yes, I think extending the bars in Exercise 3 helped. Interesting point about Shiny or Plot.ly*
- *Nice job rotating the labels in Exercise 4. Makes a big difference.*
- *Looks like you learned a lot by playing around with settings! Haha.*

**Comment by MarinStatsLectures** [comment]
thanks for the feedback :)
