### ISSUE TITLE
Peer Review of hw01

### ISSUE THREAD

**Issue by isabelchew** [STAT545-UBC-hw-2019-20/stat545-hw-MarinStatsLectures#2]
Peer-Review HW-1 for MarinStatsLectures
----------------------------------------------------
Topic                       | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style**            | :heavy_check_mark: |  |  |
**Coding strategy**         | :heavy_check_mark:  |  |  |
**Presentation: graphs**    | :heavy_check_mark: |  |  |
**Presentation: tables**    | :heavy_check_mark:  |  |  |
**Achievement, creativity** | :heavy_check_mark: |  |  |
**Ease of access**          | :heavy_check_mark: |  |  |

Remarks:

- The code was easy to read, and now that we've learnt piping, using the "%>%" will only further increase the readability of the code (i.e. we can drop the $ symbol for columns). 

- What I really liked about your work is the strong narrative running through your exploration of the data. It made it easy to follow your train of thought, and importantly, provided justification for why you did what you did.  

- The only minor thing I would comment is that the link for the youtube channel on your readme is broken, because I would have loved to visit it. Also, it would have been nice to title your presentation. But otherwise, this was a very compelling repository! :)

**Comment by MarinStatsLectures** [comment]
thanks for the feedback!  and thanks for letting me know the link was broken, ive fixed that now.  here is the link as well if you wanted to check it out:  https://www.youtube.com/marinstatlectures
