### ISSUE TITLE
Peer review HW2

### ISSUE THREAD

**Issue by jloesberg** [STAT545-UBC-hw-2019-20/stat545-hw-MarinStatsLectures#4]
I like that you included multiple ways of doing question 1.3, and I learned how to round data to a certain decimal point, which I didnt know before! You went pretty in depth to explore the variables in part 2, and I also saw some functions I havent used before. For the last graph you made in part 2, I don't think you need to select for continent before making a bar graph (it should automatically do it for you). Good job on graphs for part 3, they look great!

Good job =)

**Comment by MarinStatsLectures** [comment]
thanks for the feedback :)
