### ISSUE TITLE
Peer Review Assignment 3

### ISSUE THREAD

**Issue by srussell2416** [STAT545-UBC-hw-2019-20/stat545-hw-MarinStatsLectures#5]
Peer-Review HW-03 for Mike Marin
----------------------------------------------------
Topic                       | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style**            | :heavy_check_mark: |  |  |
**Coding strategy**         | :heavy_check_mark: |  |  |
**Presentation: graphs**    | :heavy_check_mark:  |  | |
**Presentation: tables**    | :heavy_check_mark: |   |  |
**Achievement, creativity** | :heavy_check_mark: |  |  |
**Ease of access**          | :heavy_check_mark: |  |  |

Remarks:

* Very good overall! Lots of good commentary to read.
* I started out by looking at the .md file, which is super messy and confusing! I found the html soon after, but maybe don't include the .md without figuring out how to format it cleanly?
* Very interesting comparison between Vietnam and Cambodia! I was curious about the decline in life expectancy in Cambodia myself and found out about the [genocide committed between 1975 and 1979 by the Khmer Rouge regime](https://www.history.com/topics/cold-war/the-khmer-rouge). The Cambodian genocide only ended when Vietnam invaded and overthrew the regime in 1979. This timeframe matches the decline in population and life expectancy that you noticed more closely, as the minimum Cambodian life expectancy occurred in 1977 (two years after the civil war ended). Perhaps this is why life expectancy decreased so sharply in Cambodia and not Vietnam in the 70s.

**Comment by MarinStatsLectures** [comment]
thanks for the feedback.  yeah, i agree, the .md file is a mess.  i wasn't sure what the point of keeping that around was, and now that ive figure out a few things, i will just not "keep md" as is is just a distracting mess.
