### ISSUE TITLE
Peer Review Assignment 2

### ISSUE THREAD

**Issue by srussell2416** [STAT545-UBC-hw-2019-20/stat545-hw-MarinStatsLectures#6]
Peer-Review HW-02 for Mike Marin
----------------------------------------------------
Topic                       | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style**            | :heavy_check_mark: |  |  |
**Coding strategy**         | :heavy_check_mark: |  |  |
**Presentation: graphs**    | :heavy_check_mark: |  |  |
**Presentation: tables**    | :heavy_check_mark: |   |  |
**Achievement, creativity** | :heavy_check_mark: |  |  |
**Ease of access**          | :heavy_check_mark: |  |  |

Remarks:

* Sorry for reviewing you twice in one week! I wrote up a whole review for your HW-03 before realizing it, and then I figured I might as well post it.
* Excellent work!
* You wrote so much for this, wow! You are inspiring me to write much more about all the plots I make. That's probably a good habit to get into, because then you can follow your train of thought when you look back on analyses.
* I never really liked violin plots, but that's probably because I'm used to huge datasets with too many points to jitter nicely. I like the minimalism of density plots. They're easier to translate into probability density functions.

**Comment by MarinStatsLectures** [comment]
thanks for the feedback.  i have written a lot there, as you said, so that when i look back on things, ive documented for myself what im doing and how to do certain things.
