### ISSUE TITLE
HW 3 peer review

### ISSUE THREAD

**Issue by jloesberg** [STAT545-UBC-hw-2019-20/stat545-hw-MarinStatsLectures#7]
Hi Mike,

Good job! Your exploration is very thorough and I appreciate how much time you spent looking through each part. Your graphs are all aesthetically pleasing, and I learned a lot of new code for making graphs look nice (and about the ggthemes package!). 

Your "website" ran well and the Read me file was easy to navigate. However, something funky is going on with the .md file (the text is all over the place). Its not a big deal because the html ran OK, but I'm not sure what the issue is (might be something with the output? I think other people have also had this problem).

**Comment by MarinStatsLectures** [comment]
thanks for the feedback!  yeah, i will no longer keep the .md file around as it is just distracting and adds no value.
