### ISSUE TITLE
Peer Review HW04

### ISSUE THREAD

**Issue by jgubc** [STAT545-UBC-hw-2019-20/stat545-hw-MarinStatsLectures#8]
Peer-Review HW-04 @MarinStatsLectures 
----------------------------------------------------
Topic                       | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style**            | :heavy_check_mark: |  |  |
**Coding strategy**         | :heavy_check_mark: |  |  |
**Presentation: graphs**    | :heavy_check_mark: |  |  |
**Presentation: tables**    | :heavy_check_mark: |   |  |
**Achievement, creativity** | :heavy_check_mark: |  |  |
**Ease of access**          | :heavy_check_mark: |  |  |

Remarks:
- Very nice narrative - complements your analysis.
-  Learnt few new tricks with plots - For example, a new theme (economist), manipulate color and size of trend line and positioning of plot title. Minor tricks that make a big visual impact.
- Neat analysis, easily accessible and nice narrative.

**Comment by MarinStatsLectures** [comment]
thanks for the feedback :)
